apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: avgbs2mtab-template
  annotations:
    openshift.io/display-name: "All components for AGI avgbs2mtab Web Service"
    description: >-
      "Creates all necessary components for the AGI avgbs2mtab Web Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the AGI avgbs2mtab Web Service"
    tags: "agi,gdi,avgbs2mtab,java"
    iconClass: icon-java
labels:
  createdBy: avgbs2mtab-template
parameters:
  - description: Name for Environment
    name: env 
    required: true
    value: test
  - description: Version of Image
    name: version
    required: true
    value:
  - name: CPU_LIMIT
    description: "Set Limit for cpu"
    required: true
  - name: MEMORY_LIMIT
    description: "Set Limit for Memory Usage"
    required: true
  - name: CPU_REQUEST
    description: "Set Request for cpu"
    required: true
  - name: MEMORY_REQUEST
    description: "Set Request for Memory"
    required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: avgbs2mtab-web-service  
    creationTimestamp: null
    generation: 1
    name: avgbs2mtab-web-service
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: avgbs2mtab-web-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: avgbs2mtab-web-service
          deploymentconfig: avgbs2mtab-web-service
      spec:
        containers:
        - image: sogis/avgbs2mtab-web-service
          imagePullPolicy: IfNotPresent
          name: avgbs2mtab-web-service
          ports:
          - containerPort: 8878
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - avgbs2mtab-web-service
        from:
          kind: ImageStreamTag
          name: avgbs2mtab-web-service:${version}
          namespace: agi-apps-${env}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: avgbs2mtab-service
    annotations:
      description: http port of application
    labels:
      application: avgbs2mtab-web-service
  spec:
    selector:
      deploymentconfig: avgbs2mtab-web-service
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8878
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: avgbs2mtab-web-service
    labels:
      application: avgbs2mtab-web-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/avgbs2mtab-web-service:${version}
      name: ${version}
      importPolicy:
        scheduled: true
