apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: indexupdater
  annotations:
    openshift.io/display-name: "All components for Solr Indexupdater"
    description: >-
      "Creates all necessary components for the Solr Indexupdater"
    openshift.io/long-description: >-
      "Creates all necessary components for the Solr Index Updater"
    tags: "agi,gdi,ilivalidator,java"
    iconClass: icon-java
labels:
  createdBy: indexupdater-template
parameters:
  - description: Name for Environment
    name: env
    required: true
    value: test
  - description: Version of Image
    name: version
    required: true
    value:
  - description: Set cpu Limit
    name: CPU_LIMIT
    value: "800m"
  - description: Set cpu request
    name: CPU_REQUEST
    value: "100m"
  - description: Set Memory Limit
    name: MEMORY_LIMIT
    value: "250MB"
  - description: Set Memory Request
    name: MEMORY_REQUEST
    value: "500MB"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: indexupdater
    creationTimestamp: null
    generation: 1
    name: indexupdater
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: indexupdater
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: indexupdater
          deploymentconfig: indexupdater
      spec:
        containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: >-
                {"solrProtocol":"http","solrHost":"solr-headless.solr-cloud-${env}","solrPort":8983,"solrPathQuery":"solr/gdi/select","solrPathUpdate":"solr/gdi/update","logSilenceMaxDurationSeconds":3600,"dihPollIntervalSeconds":2,"dihImportMaxDurationSeconds":900,"dihDefaultPath":"solr/gdi/dih_geodata", "logLevel":"info"}
          image: sogis/indexupdater
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: indexupdater
          ports:
          - containerPort: 8888
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - indexupdater
        from:
          kind: ImageStreamTag
          name: indexupdater:${version}
          namespace: solr-cloud-${env}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: indexupdater
    annotations:
      description: http port of application
    labels:
      application: indexupdater
  spec:
    selector:
      deploymentconfig: indexupdater
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8080
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: indexupdater
    labels:
      application: indexupdater
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/indexupdater:${version}
      name: ${version}
      importPolicy:
        scheduled: true
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      application: indexupdater
    name: indexupdater
  spec:
    host: indexupdater-${env}.apps.ocp.so.ch
    port:
      targetPort: 80
    to: 
      kind: Service
      name: indexupdater
      weight: 100 
    wildcardPolicy: None
