apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: gb2av
labels:
  template: gb2av-template
  app: gb2av
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: gb2av
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/gb2av:${TAG}
      importPolicy:
        scheduled: ${{IMPORT_POLICY_SCHEDULED}}
      name: ${TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: gb2av
  spec:
    template:
      metadata:
        labels:
          app: gb2av
          deploymentconfig: gb2av
      spec:
        containers:
        - name: gb2av
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: ${ENVIRONMENT_SHORT}
          - name: TZ
            value: Europe/Amsterdam
          envFrom:
          - secretRef:
              name: aws-secret-gb2av
          - secretRef:
              name: infogrips-secret
          - secretRef:
              name: db-secret-gretl
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1 
    replicas: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - gb2av
        from:
          kind: ImageStreamTag
          name: gb2av:${TAG}
    selector:
      app: gb2av
      deploymentconfig: gb2av
    strategy:
      type: Rolling
    revisionHistoryLimit: 10
- apiVersion: v1
  kind: Service
  metadata:
    name: gb2av
    annotations:
      description: http port of application
    labels:
      app: gb2av
      deploymentconfig: gb2av
  spec:
    selector:
      deploymentconfig: gb2av
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8080
parameters:
- name: ENVIRONMENT_SHORT
  description: "The short name of the environment the template is processed for (one of dev, test, int, prod)"
  value: test
- name: TAG
  description: "The Docker image tag to use (e.g. latest, 1.0.11)"
  value: latest
- name: IMPORT_POLICY_SCHEDULED
  description: "Regularly check for changed image (default: false)"
  value: "false"
- name: CPU_LIMIT
  description: "Set Limit for cpu"
  required: true
- name: MEMORY_LIMIT
  description: "Set Limit for Memory Usage"
  required: true
- name: CPU_REQUEST
  description: "Set Request for cpu"
  required: true
- name: MEMORY_REQUEST
  description: "Set Request for Memory"
  required: true
