apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: cadastre-web-service-template
  annotations:
    openshift.io/display-name: "All components for Cadastre Web Service"
    description: >-
      "Creates all necessary components for the Cadastre Web Service"
    openshift.io/long-description: >-
      "Creates all necessary components for the Cadastre Web Service"
    tags: "agi,gdi,cadastre-service,java"
    iconClass: icon-java
labels:
  createdBy: cadastre-web-service-template
parameters:
  - description: Name for Environment
    name: env
    required: true
    value: test
  - description: URL of DB ENV
    name: dbenv
    required: true
    value: geodb-t
  - description:
    name: dbschema
    required: true
    value: stage
  - description: Version of Image
    name: version
    required: true
    value:
  - description: CPU limit
    name: CPU_LIMIT
    value:
  - description: CPU request
    name: CPU_REQUEST
    value:
  - description: Memory limit
    name: MEMORY_LIMIT
    value:
  - description: Memory request
    name: MEMORY_REQUEST
    value:
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Image Stream of the application
    labels:
      application: cadastre-web-service
    creationTimestamp: null
    generation: 1
    name: cadastre-web-service
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: cadastre-web-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 60
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: cadastre-web-service
          deploymentconfig: cadastre-web-service
      spec:
        containers:
        - env:
            - name: DBURL
              value: 'jdbc:postgresql://${dbenv}.rootso.org/oereb?sslmode=require'
            - name: DBSCHEMA
              value: ${dbschema}
            - name: DBUSR
              valueFrom:
                secretKeyRef:
                  name: cadastre-web-service-secret
                  key: username
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: cadastre-web-service-secret
                  key: password
            - name: TMPDIR
              value: /tmp
            - name: TZ
              value: Europe/Zurich
            - name: MININTERSECTION
              value: '0.5'
          image: cadastre-web-service:${version}
          imagePullPolicy: IfNotPresent
          name: cadastre-web-service
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - cadastre-web-service
        from:
          kind: ImageStreamTag
          name: cadastre-web-service:${version}
          namespace: agi-apps-${env}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: cadastre-web-service
    annotations:
      description: http port of application
    labels:
      application: cadastre-web-service
  spec:
    selector:
      deploymentconfig: cadastre-web-service
    ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 8080
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: cadastre-web-service
    labels:
      application: cadastre-web-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: sogis/cadastre-web-service:${version}
      name: ${version}
      importPolicy:
        scheduled: true
